version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: kanban_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: kanban
      MYSQL_USER: kanbanuser
      MYSQL_PASSWORD: kanbanpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: kanban_backend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: kanbanuser
      DB_PASSWORD: kanbanpass
      DB_NAME: kanban
      DB_PORT: 3306
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data: